language: python
# Switch to container-based builds
sudo: false
# Which versions of Python to test
python:
#  - "2.7"
  - "3.6"
  - "3.7"
# Allow Python3.7 tests to fail for now
matrix:
  allow_failures:
    - python: "3.7"
# Do not have the virtualenv use system-wide site packages
virtualenv:
    system_site_packages: false
# command to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  # Clone base PlantCV
  - git clone --depth=50 https://github.com/danforthcenter/plantcv.git plantcv-base
  # Combine plantcv and plantcv-hyperspectral requirements
  - cat ./plantcv-base/requirements.txt >> requirements.txt
  # These are the packages we need
  - conda create -q -c conda-forge -n test-environment --file requirements.txt python=$TRAVIS_PYTHON_VERSION opencv=3.3 coveralls
  - source activate test-environment
  # Install base plantcv
  - cd plantcv-base; python setup.py install; cd ..
  # Install the hyperspectral package
  - python setup.py install
# command to run tests
script:
  - source activate test-environment
  - coverage run --source=plantcv setup.py test
after_success:
  coveralls
# Which branches to run build tests on
branches:
  only:
    - master
