dist: xenial
language: python
# Which versions of Python to test
python:
  - "3.6"
  - "3.7"
# Do not have the virtualenv use system-wide site packages
virtualenv:
    system_site_packages: false
# command to install dependencies
install:
  # Clone base PlantCV
  - git clone --depth=50 https://github.com/danforthcenter/plantcv.git plantcv-base
  # Combine plantcv and plantcv-hyperspectral requirements
  - cat ./plantcv-base/requirements.txt >> requirements.txt
  # Install requirements
  - pip install -r requirements.txt
  - pip install coveralls pytest
  # Install base plantcv
  - cd plantcv-base; python setup.py install; cd ..
  # Install the hyperspectral package
  - python setup.py install
# command to run tests
script:
  - coverage run --source=plantcv setup.py test
after_success:
  coveralls
# Which branches to run build tests on
branches:
  only:
    - master
